### ISSUE TITLE
Initializing Animapp

### ISSUE THREAD

**Issue by 0hl4vr4c** [sraorao/animapp_conda#2]
Hello!

First of all, thank you for sharing this amazing tool with everyone else!

I am trying to start using the Animapp but I'm facing difficulties in initializing it.
I was able to install everything by following the instructions provided in https://animapp.readthedocs.io/en/latest/, however, most likely because of my lack of basic knowledge, I cannot initialize the GUI that you show in the same page. I type in the threshold (or Animapp) command and I receive the following message: Animapp - Please run 'threshold' on an exemplar video, and then run 'animapp' on the video(s) of interest.
But I am not sure how to proceed from here. Again, I am sorry for my ignorance and probably stupid question, but how can I run the 'threshold' on my video of interest? I tried to give the path to an example video, but it didn't work (maybe because I did it wrong??). 
Any help would be really appreciated!

Thank you in advance for your time.

Best,
André

**Comment by sraorao** [comment]
Hi André,

The first step is to type `threshold` at the commandline. That should bring up a window, with a button called 'load video' at the bottom right corner. Once you set the thresholds using the slider bars, and click on 'write settings' in the botton left corner, a file called settins.yaml is created. 

The second step is to type `animapp` at the commandline. The animapp script uses the settings recorded by the threshold script in the previous step.

The message you mentioned is produced if you did not run the commands in this order. Alternatively, instead of running the `threshold` command, you could create the settings.yaml file manually in [this format](https://github.com/sraorao/animapp_conda/blob/master/animapp_pyqt5/settings.yaml). Do please let me know if it still doesn't work, and I will try to troubleshoot.

BW
Rao

**Comment by 0hl4vr4c** [comment]
Hello Rao,

Thank you for your quick reply.
In fact I was able to open the GUI this time and it seems that I am able to open the videos, even though I did the same before. I am not sure why I got a different outcome, but thank you anyway for your time and openness to share your work with us!

Best,
André
